import { useLazyQuery, useQuery, useSubscription, useMutation } from "@apollo/client";

import { GETAUTH ,TEAMS,GROUPS, SCHEDULESMATCH, EACHMATCHROSTER, SCHEDULELIVE, TEAMSTATS, GETMATCHBYID, GETTOGGLEDISABLE,TEAMDETAILS,CAISSEDASHBOARD, SINGLEROSTER} from "./graphql/query";
import { ADDGROUP,ADDHALFTIME, ADDPLAYER, ADDSUB, ADDTEAM, ADDLABEL,UPDATELABEL, CHANGEEVENTSTATUS, DROPACTOR, DROPEVENT, EDITGROUPTEAMS, LOGIN,REMOVEGROUP,REMOVEMATCHROSTER,REMOVEPLAYER,REMOVESCHEDULE,REMOVETEAM, SAVEMATCHROSTER, SCHEDULEMATCH, STANDAREVENT, SWITCHMATCHMODE, TOGGLEDISABLE, UPDATEPLAYER, UPDATETEAM, UPDATETIMERORPLAYER } from "./graphql/mutation";
import { LIVEMATCHEVENTS } from "./graphql/subscription";

export const useGetToggleSettings=()=>{
  return {
    data: {
      getTopSettings: {}
    },
    loading:false,
    refetchSettings:()=>{}
  };
}